# Spring config properties
spring.config.import=optional:file:.env[.properties]

spring.application.name=previdenciario-api

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USER}
spring.datasource.password= ${SPRING_DATASOURCE_PASSWORD}
logging.level.org.springframework.security=DEBUG